server:
  port: 7070

spring:
  #redis:
    #host: localhost
    #port: 6379
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: localhost:7070
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@gatewayResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
      enabled: true
      discovery:
        locator:
          enabled: true

  application:
    name: gateway-limiter
management:
  endpoint:
    health:
      show-details: always
