server:
  port: 6663

spring:
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: SpringBoot
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        tags: port=6663