server:
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: TestSrping
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}